var nynor = [
	['være','vere'],
	['kommer', 'kjem'],
	['jeg', 'eg'],
	['man', 'ein'],
	['ble', 'blei'],
	['bare', 'berre'],
	['noe', 'noko'],
	['noen', 'nokon'],
	['de', 'dei'],
	['si', 'seie'],
	['en', 'ein'],
	['et', 'eit'],
	['tro', 'tru'],
	['bo', 'bu'],
	['mye', 'mykje'],
	['disse', 'desse'],
	['gjør', 'gjer'],
	['bare', 'berre'],
	['fikk', 'fekk'],
	['vei', 'veg'],
	['fortsatt','framleis'],
	['finnes', 'finst'],
	['man', 'ein'],
]